### ISSUE TITLE
pip install module

### ISSUE THREAD

**Issue by Muzakie-ID** [AnonymousX1025/AnonXMusic#175]
ERROR: Ignored the following yanked versions: 1.2.3, 1.2.8, 2.0.0
ERROR: Could not find a version that satisfies the requirement py-tgcalls==0.9.7 (from versions: 0.1.0, 0.2.1, 0.3.9, 0.4.9, 0.5.5, 0.6.0, 1.0.9, 1.1.6, 1.2.1, 1.2.2, 1.2.4, 1.2.7, 1.2.9, 2.0.1, 2.0.2)
ERROR: No matching distribution found for py-tgcalls==0.9.7

**Comment by Muzakie-ID** [comment]
ERROR: Ignored the following yanked versions: 1.2.3, 1.2.8, 2.0.0
ERROR: Could not find a version that satisfies the requirement py-tgcalls==0.9.7 (from versions: 0.1.0, 0.2.1, 0.3.9, 0.4.9, 0.5.5, 0.6.0, 1.0.9, 1.1.6, 1.2.1, 1.2.2, 1.2.4, 1.2.7, 1.2.9, 2.0.1, 2.0.2)
ERROR: No matching distribution found for py-tgcalls==0.9.7

**Comment by AnonymousX1025** [comment]
> ERROR: Ignored the following yanked versions: 1.2.3, 1.2.8, 2.0.0 ERROR: Could not find a version that satisfies the requirement py-tgcalls==0.9.7 (from versions: 0.1.0, 0.2.1, 0.3.9, 0.4.9, 0.5.5, 0.6.0, 1.0.9, 1.1.6, 1.2.1, 1.2.2, 1.2.4, 1.2.7, 1.2.9, 2.0.1, 2.0.2) ERROR: No matching distribution found for py-tgcalls==0.9.7

Which os ?

**Comment by Muzakie-ID** [comment]
ubuntu

Rab, 17 Jul 2024 pukul 21.44 ˹ᴧɴσɴʏᴍσᴜs ꭙ˼ ***@***.***>
menulis:

**Comment by AnonymousX1025** [comment]
Version?

**Comment by Abishnoi69** [comment]
> ERROR: Ignored the following yanked versions: 1.2.3, 1.2.8, 2.0.0 ERROR: Could not find a version that satisfies the requirement py-tgcalls==0.9.7 (from versions: 0.1.0, 0.2.1, 0.3.9, 0.4.9, 0.5.5, 0.6.0, 1.0.9, 1.1.6, 1.2.1, 1.2.2, 1.2.4, 1.2.7, 1.2.9, 2.0.1, 2.0.2) ERROR: No matching distribution found for py-tgcalls==0.9.7

`pip install https://github.com/pytgcalls/pytgcalls/archive/dbb081ca295a74336f7ad5e1576dc021148578be.zip
`
