### ISSUE TITLE
M this is a problem

### ISSUE THREAD

**Issue by Affaffd** [AnonymousX1025/AnonXMusic#74]
ERROR: unable to download video data: HTTP Error 403: Forbidden

**Comment by Affaffd** [comment]
> خطأ: غير قادر على تنزيل بيانات الفيديو: خطأ HTTP 403: محظور

**Comment by Abishnoi69** [comment]
> ERROR: unable to download video data: HTTP Error 403: Forbidden

Change  `IP`

**Comment by Abishnoi69** [comment]
> how to change ip ?

Try Google

**Comment by KSKOP69** [comment]
> Try Google

i dont have google now. You seems to be pro. You tell.

**Comment by Abishnoi69** [comment]
> > Try Google
> 
> i dont have google now. You seems to be pro. You tell.

I don't have vps :(

**Comment by AnonymousX1025** [comment]
> ERROR: unable to download video data: HTTP Error 403: Forbidden

YouTube blacklisted your ip.
